/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salvalma;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Fernando Araujo Nascimento, Thais Andrade Couto, Juliana Ferreira Damascena, Gisele Gomes Oliveira, Alesson Silva Boges e Thais Costa 431
 */
public class cadastrar extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement p;
    private ResultSet r;
    
    /**
     * Creates new form cadastrar
     */
    public cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbUnidade = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisaPorCodigo = new javax.swing.JTextField();
        btnBuscarPorCodigo = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAvanc = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        jButton5.setText("<<");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NOME DO PRODUTO");

        txtNome.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("PREÇO");

        txtPreco.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CODIGO");

        txtCod.setEditable(false);
        txtCod.setBackground(new java.awt.Color(204, 204, 204));

        txtQtd.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("QUANTIDADE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("MEDIDO EM");

        cbUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidade", "Kilo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbUnidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addComponent(txtPreco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Pesquisar por codigo :");

        txtPesquisaPorCodigo.setBackground(new java.awt.Color(204, 204, 204));

        btnBuscarPorCodigo.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 12)); // NOI18N
        btnBuscarPorCodigo.setText("ir");
        btnBuscarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorCodigoActionPerformed(evt);
            }
        });

        btnFirst.setText("<<");
        btnFirst.setEnabled(false);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnVoltar.setText("<");
        btnVoltar.setEnabled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAvanc.setText(">");
        btnAvanc.setEnabled(false);
        btnAvanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.setEnabled(false);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisaPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPorCodigo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnFirst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAvanc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLast)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(33, 33, 33)
                        .addComponent(btnBuscar)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLast)
                            .addComponent(btnAvanc)
                            .addComponent(btnVoltar)
                            .addComponent(btnFirst)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPesquisaPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorCodigo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtCod.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtQtd.setText("");
        cbUnidade.setSelectedIndex(0);
        
        btnExcluir.setEnabled(false);
        btnLast.setEnabled(false);
        btnAvanc.setEnabled(false);
        btnVoltar.setEnabled(false);
        btnFirst.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtCod.getText().equals("")) {
            txtCod.setText(adicionarProduto()+"");
        } else {
            editarProduto();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarProdutos();
        btnExcluir.setEnabled(true);
        btnLast.setEnabled(true);
        btnAvanc.setEnabled(true);
        btnVoltar.setEnabled(true);
        btnFirst.setEnabled(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAvancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancActionPerformed
        try {
            if (r != null) {
                if (r.next()) {
                    txtCod.setText(r.getInt("COD")+"");
                    txtNome.setText(r.getString("NOME"));
                    txtPreco.setText(r.getDouble("PRECO")+"");
                    txtQtd.setText(r.getInt("QTD")+"");
                    cbUnidade.setSelectedIndex(r.getInt("UN"));
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }//GEN-LAST:event_btnAvancActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            if (r != null) {
                if (r.last()) {
                    txtCod.setText(r.getInt("COD")+"");
                    txtNome.setText(r.getString("NOME"));
                    txtPreco.setText(r.getDouble("PRECO")+"");
                    txtQtd.setText(r.getInt("QTD")+"");
                    cbUnidade.setSelectedIndex(r.getInt("UN"));
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            if (r != null) {
                if (r.first()) {
                    txtCod.setText(r.getInt("COD")+"");
                    txtNome.setText(r.getString("NOME"));
                    txtPreco.setText(r.getDouble("PRECO")+"");
                    txtQtd.setText(r.getInt("QTD")+"");
                    cbUnidade.setSelectedIndex(r.getInt("UN"));
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            if (r != null) {
                if (r.relative(-1)) {
                    txtCod.setText(r.getInt("COD")+"");
                    txtNome.setText(r.getString("NOME"));
                    txtPreco.setText(r.getDouble("PRECO")+"");
                    txtQtd.setText(r.getInt("QTD")+"");
                    cbUnidade.setSelectedIndex(r.getInt("UN"));
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirProduto();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorCodigoActionPerformed
        if (!txtPesquisaPorCodigo.getText().equals("")) {
            buscarProdutoPorCodigo();
        }
    }//GEN-LAST:event_btnBuscarPorCodigoActionPerformed

    private void buscarProdutoPorCodigo() {
        String sql = "SELECT * FROM PRODUTO WHERE COD = ?";
        
        if (con == null) 
            con = new ConexaoBd().getConnection();
        try {
            p = con.prepareStatement(sql);
            p.setInt(1, Integer.valueOf(txtPesquisaPorCodigo.getText()));
            
            r = p.executeQuery();
            
            if (r.next()) {
                txtCod.setText(r.getInt("COD")+"");
                txtNome.setText(r.getString("NOME"));
                txtPreco.setText(r.getDouble("PRECO")+"");
                txtQtd.setText(r.getInt("QTD")+"");
                cbUnidade.setSelectedIndex(r.getInt("UN"));
            }
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }
    
    private void buscarProdutos() {
        String sql = "SELECT * FROM PRODUTO";
        
        if (con == null) 
            con = new ConexaoBd().getConnection();
        try {
            p = con.prepareStatement(sql);
            r = p.executeQuery();
            
            if (r.next()) {
                txtCod.setText(r.getInt("COD")+"");
                txtNome.setText(r.getString("NOME"));
                txtPreco.setText(r.getDouble("PRECO")+"");
                txtQtd.setText(r.getInt("QTD")+"");
                cbUnidade.setSelectedIndex(r.getInt("UN"));
            }
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }
    
    private int adicionarProduto() {
        Integer cod = null;
        
        String sql = "SELECT MAX(COD) AS codigo FROM PRODUTO";
        
        try {
            
            if (con == null)
                con = new ConexaoBd().getConnection();
            p = con.prepareStatement(sql);
            r = p.executeQuery();
            
            while (r.next()) {
                cod = r.getInt("codigo") + 1;
            }
            
            sql = "INSERT INTO PRODUTO (COD, NOME, PRECO, QTD, UN) "
                    + "VALUES (?, ?, ?, ?, ?)";
            
            p = con.prepareStatement(sql);
            p.setInt(1, cod);
            p.setString(2, txtNome.getText());
            p.setDouble(3, Double.valueOf(txtPreco.getText().replace(",", ".")));
            p.setInt(4, Integer.valueOf(txtQtd.getText()));
            p.setInt(5, cbUnidade.getSelectedIndex());
            
            p.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        } finally {
            try {
                p.close();
                r.close();
            } catch (SQLException e) {
                System.out.println("Erro: "+e);
            }
        }
        
        return cod;
    }
    
    private void editarProduto() {
        String sql = "UPDATE PRODUTO SET "
                    + "NOME = ?, "
                    + "PRECO = ?, "
                    + "QTD = ?, "
                    + "UN = ? "
                    + "WHERE COD = ?";
        
        try {
            
            if (con == null)
                con = new ConexaoBd().getConnection();
            
            p = con.prepareStatement(sql);
            p.setString(1, txtNome.getText());
            p.setDouble(2, Double.valueOf(txtPreco.getText().replace(",", ".")));
            p.setInt(3, Integer.valueOf(txtQtd.getText()));
            p.setInt(4, cbUnidade.getSelectedIndex());
            p.setInt(5, Integer.valueOf(txtCod.getText()));
            
            p.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }
    
    private void excluirProduto() {
        String sql = "DELETE FROM PRODUTO "
                    + "WHERE COD = ?";
        
        try {
            
            if (con == null)
                con = new ConexaoBd().getConnection();
            
            p = con.prepareStatement(sql);
            p.setInt(1, Integer.valueOf(txtCod.getText()));
            
            p.executeUpdate();
            
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
        
        buscarProdutos();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanc;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarPorCodigo;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbUnidade;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisaPorCodigo;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
