/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salvalma;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Fernando Araujo Nascimento, Thais Andrade Couto, Juliana Ferreira Damascena, Gisele Gomes Oliveira, Alesson Silva Boges  431
 */
public class venda2 extends javax.swing.JFrame {

    private Connection con;
    private PreparedStatement p;
    private ResultSet r;
    private ArrayList<String[]> compra;
    private Double total;

    /**
     * Creates new form venda2
     */
    public venda2(ArrayList<String[]> c) {
        initComponents();
        compra = c;
        total = 0.0;
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("NOME");
        modelo.addColumn("QUANTIDADE");
        modelo.addColumn("VALOR");
        
        for (String[] s : c) {
            modelo.addRow(new Object[]{s[1], s[2], s[3]});
            total += Double.valueOf(s[3]);
        }
       
        txtTotal.setText(total+"");
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        cbDinheiro = new javax.swing.JCheckBox();
        cbCartao = new javax.swing.JCheckBox();
        txtValorCartao = new javax.swing.JTextField();
        txtValorDinheiro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        btnExclItem = new javax.swing.JButton();
        btnCalcTroco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "QUANTIDADE", "VALOR"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TOTAL = ");

        txtTotal.setEditable(false);
        txtTotal.setText(".");

        cbDinheiro.setText("DINHEIRO");
        cbDinheiro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDinheiroItemStateChanged(evt);
            }
        });

        cbCartao.setText("CARTÃO");
        cbCartao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCartaoItemStateChanged(evt);
            }
        });

        txtValorCartao.setEditable(false);

        txtValorDinheiro.setEditable(false);
        txtValorDinheiro.setToolTipText("Valor no dinheiro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("VALOR RECEBIDO =");

        txtValorRecebido.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TROCO =");

        txtTroco.setEditable(false);

        btnFinalizar.setText("FINALIZAR");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnExclItem.setText("EXCLUIR ITEM");
        btnExclItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExclItemActionPerformed(evt);
            }
        });

        btnCalcTroco.setText("Calcular");
        btnCalcTroco.setEnabled(false);
        btnCalcTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcTrocoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExclItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDinheiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(19, 19, 19)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtValorDinheiro)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCartao)
                                .addGap(63, 63, 63)
                                .addComponent(txtValorCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTroco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcTroco)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnExclItem)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDinheiro)
                    .addComponent(txtValorDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcTroco))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCartao))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDinheiroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDinheiroItemStateChanged
        if (cbDinheiro.isSelected()) {
            txtValorDinheiro.setEditable(true);
            txtValorRecebido.setEditable(true);
            btnCalcTroco.setEnabled(true);
        } else {
            txtValorDinheiro.setEditable(false);
            txtValorRecebido.setEditable(false);
            btnCalcTroco.setEnabled(false);
        }
    }//GEN-LAST:event_cbDinheiroItemStateChanged

    private void btnExclItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExclItemActionPerformed
        
    }//GEN-LAST:event_btnExclItemActionPerformed

    private void cbCartaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCartaoItemStateChanged
        if (cbCartao.isSelected()) {
            if (cbDinheiro.isSelected() && !txtValorDinheiro.getText().equals("")) {
                Double vn = Double.valueOf(txtTotal.getText()) - Double.valueOf(txtValorDinheiro.getText());
                txtValorCartao.setText(vn+"");
            }
            txtValorCartao.setEditable(true);
        } else {
            txtValorCartao.setEditable(false);
        }
    }//GEN-LAST:event_cbCartaoItemStateChanged

    private void btnCalcTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcTrocoActionPerformed
        if (!txtValorDinheiro.getText().equals("") && !txtValorRecebido.getText().equals("")) {
            Double troco = Double.valueOf(txtValorRecebido.getText()) - Double.valueOf(txtValorDinheiro.getText());
            txtTroco.setText(troco+"");
        } else {
            JOptionPane.showMessageDialog(null, "Insira o valor a ser pago em dinheiro e o valor recebido.");
        }
    }//GEN-LAST:event_btnCalcTrocoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        Integer caixa_id = null;
        
        String sql = "SELECT ID FROM CAIXA";
        
        try {
            
            if (con == null)
                con = new ConexaoBd().getConnection();
            
            p = con.prepareStatement(sql);
            r = p.executeQuery();
            
            if (r.last()) {
                caixa_id = r.getInt("ID");
            }
            
            sql = "SELECT MAX(ID) AS idd FROM VENDA";
            p = con.prepareStatement(sql);
            r = p.executeQuery();
            
            int new_id;
            if (r.next()) {
                new_id = r.getInt("idd") + 1;
            } else {
                new_id = 0;
            }
            
            sql = "INSERT INTO VENDA (ID, TOTAL, CAIXA_ID) VALUES (?, ?, ?)";
            p = con.prepareStatement(sql);
            p.setInt(1, new_id);
            p.setDouble(2, Double.valueOf(txtTotal.getText()));
            p.setInt(3, caixa_id);            
            p.executeUpdate();
            
            sql = "INSERT INTO VENDA_PRODUTOS (VENDA_ID, PRODUTO_COD, QTD) VALUES (?, ?, ?)";
            for (String[] s : compra) {
                p = con.prepareStatement(sql);
                p.setInt(1, new_id);
                p.setInt(2, Integer.valueOf(s[0]));
                p.setInt(3, Integer.valueOf(s[2]));  
                p.executeUpdate();
            }
            
            sql = "INSERT INTO VENDA_PAGT (VENDA_ID, FORMA_PAGT_ID, VALOR, TROCO) VALUES (?, ?, ?, ?)";
            if (cbDinheiro.isSelected()) {
                p = con.prepareStatement(sql);
                p.setInt(1, new_id);
                p.setInt(2, 0);
                p.setDouble(3, Double.valueOf(txtValorDinheiro.getText()));  
                p.setDouble(4, Double.valueOf(txtTroco.getText()));  
                p.executeUpdate();
            }
            sql = "INSERT INTO VENDA_PAGT (VENDA_ID, FORMA_PAGT_ID, VALOR, TROCO) VALUES (?, ?, ?, ?)";
            if (cbCartao.isSelected()) {
                p = con.prepareStatement(sql);
                p.setInt(1, new_id);
                p.setInt(2, 1);
                p.setDouble(3, Double.valueOf(txtValorCartao.getText()));
                p.setDouble(4, 0);
                p.executeUpdate();
            }
            
            this.dispose();
        } catch (SQLException ex) {
            System.out.println("Erro: "+ex);
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venda2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venda2(new ArrayList<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcTroco;
    private javax.swing.JButton btnExclItem;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JCheckBox cbCartao;
    private javax.swing.JCheckBox cbDinheiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    private javax.swing.JTextField txtValorCartao;
    private javax.swing.JTextField txtValorDinheiro;
    private javax.swing.JTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables
}
